version: "3.8"

services:
  app:
    container_name: angular-prod
    image: angular-prod
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src

    ports:
      - 80:80
